spring:

  quartz:
    wait-for-jobs-to-complete-on-shutdown: false
    job-store-type: jdbc
    overwrite-existing-jobs: true

    jdbc:
      initialize-schema: always

    properties:
      org.quartz.jobStore.isClustered: true
      org.quartz.scheduler.instanceId: AUTO
      org.quartz.scheduler.skipUpdateCheck: true
      org.quartz.threadPool.threadCount: 2

  h2:
    console.enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/testdb
    username: sa
    password: password

  jpa:
    hibernate.ddl-auto: create

  mail:

    host: email-smtp.eu-west-1.amazonaws.com
    username: AKIA3QRJDSTT4P7LI2NJ
    password: BDVKBQLtJH5DFJ3isJMP80afrFXxjyIOKlMNrdyHw7aD
    properties.mail:

      transport.protocol: smtp
      smtp:

        port: 25
        auth: true
        starttls:

          enable: true
          required: true
logging:

  level.org:
    springframework.data.jpa: TRACE

heist:
  levelUpTime: 86400

java:
  runtime:
    version: 17